server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors: #전체 cors 설정
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowedCredentials: true
      routes: #라우트 설정
        - id: member-service
          predicates:
            - Path=/member-service/**
          filters:
            - StripPrefix=1 #첫번째 접두어를 제거후에 member-service로 전달
          uri: lb://member-service
        - id: ordering-service
          predicates:
            - Path=/ordering-service/**
          filters:
            - StripPrefix=1 #첫번째 접두어를 제거후에 member-service로 전달
          uri: lb://ordering-service
        - id: product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1 #첫번째 접두어를 제거후에 member-service로 전달
          uri: lb://product-service
